package com.ec.bond.utils.validations

enum class ValidationResult {
    SUCCESS,
    ERROR_EMAIL_4,
    ERROR_EMAIL_6,
    INVALID_EMAIL,
    ERROR_EMAIL,
    ERROR_PASSWORD,
    EMPTY_EMAIL,
    EMPTY_PASSWORD,
    EMPTY_NAME,
    EMPTY_PHONE,
    VALID_PHONE,
    EMPTY_GENDER,
    SHORT_NOTE,
    ERROR_TERMS,
    ERROR_PASSWORD_TOO_SMALL,
    ERROR_PASSWORD_TOO_LONG,
    EMPTY_LOCATION,
    EMPTY_TITLE,
    EMPTY_START_DATE,
    EMPTY_END_DATE,
    EMPTY_START_TIME,
    EMPTY_END_TIME,
    EMPTY_DESCRIPTION,
    EMPTY_FILE
}